mkdir "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics"
mkdir "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry"
mkdir "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry\matrix"
copy "..\src\matrix.h" "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry\matrix\matrix.h"
copy "..\src\matrix.c" "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry\matrix\matrix.c"