mkdir "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics"
mkdir "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry"
mkdir "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry\point"
copy "..\src\point.h" "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry\point\point.h"
copy "..\src\point.c" "c:\Program Files (x86)\CodeBlocks\MinGW\include\libs\graphics\geometry\point\point.c"